version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  product-finder-alexa: # name of the first service
    container_name: productfinder-alexa
    build: . # specify the directory of the Dockerfile
    ports:
      - "7002:3000"
    mem_limit: 1024m
    networks:
      - productfinder-network
networks:
  productfinder-network: